apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production-cluster
  region: us-east-1

vpc:
  id: "vpc-089c2acac43849c77"  # Replace with your VPC ID
  subnets:
    public:
      us-east-1a: { id: "subnet-095c3ede71378a293" }  # Replace with your public subnet ID in us-east-1a
      us-east-1b: { id: "subnet-07079b0ec7fc8a8ff" }  # Replace with your public subnet ID in us-east-1b
    private:
      us-east-1a: { id: "subnet-09b75ecb2752a9702" }  # Replace with your private subnet ID in us-east-1a
      us-east-1b: { id: "subnet-012ac7dcc3c627c43" }  # Replace with your private subnet ID in us-east-1b

nodeGroups:
  - name: worker-nodes
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    privateNetworking: true  # Ensures nodes are deployed in private subnets
    volumeSize: 8
    ssh:
      allow: true  # Allow SSH access to nodes
      publicKeyName: sftp
    # securityGroups:
    #   attachIDs:
    #     - sg-0cf90e5bf3d49ae21  # Replace with your security group ID
    # iam:
    #   withAddonPolicies:
    #     albIngress: true  # Optional, if using an ALB ingress controller
