
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-095c3ede71378a293  # Specify subnet IDs
    # service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0eed70afab6c31589  # Specify the security group ID for the ALB

spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
